export const actionType = {
    BUY_LAPTOP: 'BUY_LAPTOP',
    BUY_MOBILE: 'BUY_MOBILE' ,
    FETCH_USER_REQUEST: 'FETCH_USER_REQUEST',
    FETCH_USER_RESPONSE: 'FETCH_USER_SUCCESS',
    STORE_CACHE_USER:'STORE_CACHE_USER'
}
